import { afterEach, describe, expect, it } from 'vitest';
import { emitCore } from '../../src/emitters/claude/core.js';
import { loadProject } from '../../src/loader/index.js';
import { makeTree, removeTree, VALID_PRECEPTS } from '../helpers.js';
import { FIXTURE_VERSION, findLoreWords, fixtureProject } from './fixtures.js';

const cleanups: string[] = [];
afterEach(() => {
  while (cleanups.length > 0) removeTree(cleanups.pop()!);
});

function fixture(deckYaml?: string) {
  const { project, roots } = fixtureProject(deckYaml);
  cleanups.push(...roots);
  return project;
}

const BASE_OPTS = {
  version: FIXTURE_VERSION,
  gatedTexts: new Set<string>(),
  agentIds: new Set<string>(),
  adversarialIds: new Set<string>(),
};
const GATED_OPTS = {
  ...BASE_OPTS,
  gatedTexts: new Set(['Never commit credentials, tokens, or secrets.']),
};

describe('emitCore', () => {
  it('matches the golden core emission', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toMatchSnapshot();
  });

  it('starts with the generator notice', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core.split('\n')[0]).toBe(
      `<!-- generated by arcana v${FIXTURE_VERSION} from deck.yaml — edit deck.yaml, not this file -->`,
    );
  });

  it('inlines conduct bindings one line each', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('- Never commit credentials, tokens, or secrets.');
    expect(core).toContain('- All public API changes are versioned and documented.');
  });

  it('states the hard-rule contract: surface conflicts, never break a rule', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('These rules are hard.');
    expect(core).toContain('stop\nand surface the conflict — do not break the rule.');
  });

  it('instructs one reconciled verdict when several reviews fire together', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('reconcile their findings');
    expect(core).toContain('not a pile of contradictions');
  });

  it('marks critical conduct as gated only when gates are emitted', () => {
    const ungated = emitCore(fixture(), BASE_OPTS);
    expect(ungated).not.toContain('commit gate');
    const gated = emitCore(fixture(), GATED_OPTS);
    expect(gated).toContain('- Never commit credentials, tokens, or secrets. (a commit gate enforces this)');
    expect(gated).not.toContain('documented. (a commit gate enforces this)');
  });

  it('emits routing lines, not checklists', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain(
      '- Before each commit: if the changes touch `**/auth/**`, review them against arcana/cards/hermit.md (security).',
    );
    expect(core).toContain(
      '- Before opening a pull request: review the changes against arcana/cards/justice.md (correctness).',
    );
    expect(core).toContain(
      '- When adding a new dependency: review the change against arcana/cards/hermit.md (security).',
    );
    expect(core).toContain(
      '- When making any database schema change, migration, or altering table structure: read and follow arcana/rites/migration.md before starting.',
    );
    // checklist bodies stay out of the core
    expect(core).not.toContain('security auditor');
    expect(core).not.toContain('Verify claims against the code.');
  });

  it('emits a continuous review line for glob-only vigils', () => {
    const project = fixture(
      `version: 1
cards:
  - id: hermit
    vigils:
      globs: ["src/payments/**"]
      moments: []
      changes: []
`,
    );
    const core = emitCore(project, BASE_OPTS);
    expect(core).toContain(
      '- When working in files matching `src/payments/**`: review your changes against arcana/cards/hermit.md (security) before finishing.',
    );
  });

  it('emits the severity contract in plain labels', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('- note — mention it in your summary; do not act on it.');
    expect(core).toContain('- minor issue — fix it if the fix is cheap and local, otherwise flag it.');
    expect(core).toContain('- must-fix — fix it before declaring the work done.');
    expect(core).toContain('- blocker — stop and ask the user before proceeding.');
  });

  it('omits empty sections for a minimal deck', () => {
    const registry = makeTree({ 'precepts.md': VALID_PRECEPTS });
    const root = makeTree({ 'deck.yaml': 'version: 1\n' });
    cleanups.push(registry, root);
    const project = loadProject(root, { registryDir: registry });
    const core = emitCore(project, BASE_OPTS);
    expect(core).not.toContain('## Conduct');
    expect(core).not.toContain('## Required workflows');
    expect(core).not.toContain('## Required reviews');
    expect(core).toContain('## Working principles');
  });

  it('adds the clean-room dispatch contract when an adversarial audit is present', () => {
    const withAudit = {
      ...BASE_OPTS,
      agentIds: new Set(['devil']),
      adversarialIds: new Set(['devil']),
    };
    const project = fixture('version: 1\ncards:\n  - id: hermit\n  - id: devil\n');
    const core = emitCore(project, withAudit);
    expect(core).toContain('adversarial audits that try to break the change');
    expect(core).toContain('hand it only the diff and the task statement — never your');
    expect(core).toContain('Treat every reproduction it');
  });

  it('omits the clean-room note when no adversarial audit is present', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).not.toContain('clean-room');
    expect(core).not.toContain('adversarial audits');
  });

  it('contains no lore vocabulary', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(findLoreWords(core)).toEqual([]);
  });
});
