import { afterEach, describe, expect, it } from 'vitest';
import { emitCore } from '../../src/emitters/claude/core.js';
import { loadProject } from '../../src/loader/index.js';
import { makeTree, removeTree, VALID_PRECEPTS } from '../helpers.js';
import { FIXTURE_VERSION, findLoreWords, fixtureProject } from './fixtures.js';

const cleanups: string[] = [];
afterEach(() => {
  while (cleanups.length > 0) removeTree(cleanups.pop()!);
});

function fixture(deckYaml?: string) {
  const { project, roots } = fixtureProject(deckYaml);
  cleanups.push(...roots);
  return project;
}

// Base fixture: hermit review (pre-commit + globs + dependency-add), justice audit (pre-pr).
const BASE_OPTS = {
  version: FIXTURE_VERSION,
  gatedTexts: new Set<string>(),
  hasAudits: true,
};
const GATED_OPTS = {
  ...BASE_OPTS,
  gatedTexts: new Set(['Never commit credentials, tokens, or secrets.']),
};
// A review-only deck (hermit alone) for the no-audit paths.
const REVIEW_ONLY = 'version: 1\ncards:\n  - id: hermit\n';
const REVIEW_OPTS = { ...BASE_OPTS, hasAudits: false };

describe('emitCore', () => {
  it('matches the golden core emission', () => {
    expect(emitCore(fixture(), BASE_OPTS)).toMatchSnapshot();
  });

  it('starts with the generator notice', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core.split('\n')[0]).toBe(
      `<!-- generated by arcana v${FIXTURE_VERSION} from deck.yaml — edit deck.yaml, not this file -->`,
    );
  });

  it('inlines conduct bindings one line each', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('- Never commit credentials, tokens, or secrets.');
    expect(core).toContain('- All public API changes are versioned and documented.');
  });

  it('states the hard-rule contract: surface conflicts, never break a rule', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('These rules are hard.');
    expect(core).toContain('stop\nand surface the conflict — do not break the rule.');
  });

  it('marks critical conduct as gated only when gates are emitted', () => {
    const ungated = emitCore(fixture(), BASE_OPTS);
    expect(ungated).not.toContain('commit gate');
    const gated = emitCore(fixture(), GATED_OPTS);
    expect(gated).toContain(
      '- Never commit credentials, tokens, or secrets. (a commit hook checks this)',
    );
    expect(gated).not.toContain('documented. (a commit hook checks this)');
  });

  it('routes review vigils to the checklist and audit vigils to the agent', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    // hermit: review-mode moment with globs, plus a change vigil
    expect(core).toContain(
      '- Before each commit: if the changes touch `**/auth/**`, review them against arcana/cards/hermit.md (security).',
    );
    expect(core).toContain(
      '- When adding a new dependency: review the change against arcana/cards/hermit.md (security).',
    );
    // justice: audit-mode moment dispatches the agent to break the change
    expect(core).toContain(
      '- Before opening a pull request: have the `justice` agent try to break the changes (correctness).',
    );
    expect(core).toContain(
      '- When making any database schema change, migration, or altering table structure: read and follow arcana/rites/migration.md before starting.',
    );
    // checklist bodies stay out of the core
    expect(core).not.toContain('security auditor');
    expect(core).not.toContain('Verify claims against the code.');
  });

  it('emits a continuous review line for glob-only vigils', () => {
    const project = fixture(
      'version: 1\ncards:\n  - id: hermit\n    vigils:\n      globs: ["src/payments/**"]\n      moments: []\n      changes: []\n',
    );
    const core = emitCore(project, REVIEW_OPTS);
    expect(core).toContain(
      '- When working in files matching `src/payments/**`: review your changes against arcana/cards/hermit.md (security) before finishing.',
    );
  });

  it('emits the severity contract in plain labels', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('- note — mention it in your summary; do not act on it.');
    expect(core).toContain('- minor issue — fix it if the fix is cheap and local, otherwise flag it.');
    expect(core).toContain('- must-fix — fix it before declaring the work done.');
    expect(core).toContain('- blocker — stop and ask the user before proceeding.');
  });

  it('omits empty sections for a minimal deck', () => {
    const registry = makeTree({ 'precepts.md': VALID_PRECEPTS });
    const root = makeTree({ 'deck.yaml': 'version: 1\n' });
    cleanups.push(registry, root);
    const project = loadProject(root, { registryDir: registry });
    const core = emitCore(project, REVIEW_OPTS);
    expect(core).not.toContain('## Conduct');
    expect(core).not.toContain('## Required workflows');
    expect(core).not.toContain('## Required reviews');
    expect(core).toContain('## Working principles');
  });

  it('explains the clean-room dispatch contract when audits are present', () => {
    const core = emitCore(fixture(), BASE_OPTS);
    expect(core).toContain('An audit is a review run at higher intensity');
    expect(core).toContain('hand it only the diff and the task statement');
    expect(core).toContain('Treat every');
    expect(core).toContain('reconcile the findings into one verdict');
  });

  it('omits the clean-room note and uses review-only synthesis when there are no audits', () => {
    const core = emitCore(fixture(REVIEW_ONLY), REVIEW_OPTS);
    expect(core).not.toContain('clean-room');
    expect(core).not.toContain('An audit is a review');
    expect(core).toContain('reconcile their findings and');
    expect(core).toContain('not a pile of contradictions');
  });

  it('inserts a preamble verbatim after the intro, ahead of the generated rules', () => {
    const registry = makeTree({ 'precepts.md': VALID_PRECEPTS });
    const root = makeTree({
      'deck.yaml': 'version: 1\npreamble: src/preamble.md\n',
      'src/preamble.md': '## House rules\n\nAlways run the linter.\n',
    });
    cleanups.push(registry, root);
    const project = loadProject(root, { registryDir: registry });
    const core = emitCore(project, REVIEW_OPTS);
    expect(core).toContain('## House rules\n\nAlways run the linter.');
    // preamble sits between the intro and Working principles
    expect(core.indexOf('## House rules')).toBeLessThan(core.indexOf('## Working principles'));
  });

  it('compiles the pull-request policy into a section when set', () => {
    const project = fixture(
      'version: 1\ncards:\n  - id: justice\npull_requests:\n  require_audit: true\n  agent_may_merge: true\n',
    );
    const core = emitCore(project, BASE_OPTS);
    expect(core).toContain('## Pull requests');
    expect(core).toContain('Before opening a pull request, run the required audits above');
    expect(core).toContain('You may merge a pull request yourself once you trust it');
    expect(core).toContain('never land changes by committing');
  });

  it('omits the pull-request section when the policy is off', () => {
    const core = emitCore(fixture(REVIEW_ONLY), REVIEW_OPTS);
    expect(core).not.toContain('## Pull requests');
  });

  it('emits only the requested pull-request clauses', () => {
    const auditOnly = fixture(
      'version: 1\ncards:\n  - id: justice\npull_requests:\n  require_audit: true\n',
    );
    const auditCore = emitCore(auditOnly, BASE_OPTS);
    expect(auditCore).toContain('Before opening a pull request');
    expect(auditCore).not.toContain('You may merge a pull request yourself');

    const mergeOnly = fixture(
      'version: 1\ncards:\n  - id: justice\npull_requests:\n  agent_may_merge: true\n',
    );
    const mergeCore = emitCore(mergeOnly, BASE_OPTS);
    expect(mergeCore).toContain('## Pull requests');
    expect(mergeCore).toContain('You may merge a pull request yourself');
    expect(mergeCore).not.toContain('Before opening a pull request, run the required audits');
  });

  it('contains no lore vocabulary', () => {
    expect(findLoreWords(emitCore(fixture(), BASE_OPTS))).toEqual([]);
  });
});
