import { loadProject, type Project } from '../../src/loader/index.js';
import { makeTree, VALID_CARD, VALID_PRECEPTS, VALID_RITE } from '../helpers.js';

export const FIXTURE_VERSION = '0.0.0-test';

/**
 * A representative project: one card with glob+moment+change vigils, one card
 * with a pre-pr moment only, one rite, two conduct bindings (one critical).
 */
export function fixtureProject(deckYaml?: string): { project: Project; roots: string[] } {
  const justice = `---
id: justice
arcanum: 11
title: Justice
domain: correctness
default_vigils:
  moments: [pre-pr]
severity_default: portent
requires_isolation: preferred
model_hint: strong
---
You are reviewing the full change set for correctness.

- Verify claims against the code.
`;
  const registry = makeTree({
    'cards/09-hermit.md': VALID_CARD,
    'cards/11-justice.md': justice,
    'rites/pentacles/migration.md': VALID_RITE,
    'precepts.md': VALID_PRECEPTS,
  });
  const root = makeTree({
    'deck.yaml':
      deckYaml ??
      `version: 1
cards:
  - id: hermit
  - id: justice
rites:
  - id: migration
bindings:
  conduct:
    - text: "Never commit credentials, tokens, or secrets."
      critical: true
    - text: "All public API changes are versioned and documented."
`,
  });
  return { project: loadProject(root, { registryDir: registry }), roots: [registry, root] };
}

/**
 * Lore vocabulary that must never reach agent-facing prose (§ Goals 4).
 * arcana/ file paths are sanctioned by the repo layout (§5) and scrubbed
 * before matching; the ward comment syntax is part of the mechanism itself.
 */
const LORE_PATTERNS: Array<[string, RegExp]> = [
  ['vigil', /\bvigils?\b/i],
  ['arcanum', /\barcanums?\b/i],
  ['tarot', /\btarot\b/i],
  ['rite', /\brites?\b/i],
  ['card', /\bcards?\b/i],
  ['deck', /\bdecks?\b/i],
  ['whisper', /\bwhispers?\b/i],
  ['omen', /\bomens?\b/i],
  ['portent', /\bportents?\b/i],
  ['doom', /\bdooms?\b/i],
  ['apocrypha', /\bapocryphal?\b/i],
  ['the hermit', /\bthe hermit\b/i],
];

export function findLoreWords(text: string): string[] {
  const scrubbed = text
    .replace(/\S*arcana\/\S*/g, ' ') // sanctioned reference paths
    .replace(/`[^`\n]*`/g, ' ') // inline code: ids and syntax, not prose
    .replace(/^<!-- generated by arcana .* -->$/gm, ' ') // human-facing notices
    .replace(/^\/\/ generated by arcana .*$/gm, ' ')
    .replace(/^<!-- arcana:hash:sha256 .* -->$/gm, ' ')
    .replace(/^\/\/ arcana:hash:sha256 .*$/gm, ' ');
  return LORE_PATTERNS.filter(([, re]) => re.test(scrubbed)).map(([w]) => w);
}
