// generated by arcana v0.1.0 from deck.yaml — edit deck.yaml, not this file

export const secretScan = true;
export const forcePushBlocked = true;
export const knownReviewIds = ["hermit","justice","hierophant","temperance","strength"];
export const gates = [
  {
    "id": "hermit",
    "domain": "security",
    "reference": "arcana/cards/hermit.md",
    "globs": [
      "**/auth/**",
      "**/*secret*",
      "**/*token*",
      "**/*credential*",
      "**/middleware/**",
      "**/session/**"
    ],
    "moments": [
      "pre-commit"
    ]
  },
  {
    "id": "justice",
    "domain": "correctness",
    "reference": "arcana/cards/justice.md",
    "globs": [],
    "moments": [
      "pre-pr"
    ]
  },
  {
    "id": "temperance",
    "domain": "proportion",
    "reference": "arcana/cards/temperance.md",
    "globs": [],
    "moments": [
      "pre-pr"
    ]
  }
];
// arcana:hash:sha256 531f625415abf1360fefcb01fd7c8e846dd5ed1182a369f25bcef21fa010c403
