// generated by arcana v0.1.0 from deck.yaml — edit deck.yaml, not this file

export const secretScan = true;
export const forcePushBlocked = true;
export const protectedBranches = ["main"];
export const knownReviewIds = ["hermit","justice","hierophant","temperance","strength","devil"];
export const gates = [
  {
    "id": "hermit",
    "domain": "security",
    "reference": "arcana/cards/hermit.md",
    "globs": [
      "**/auth/**",
      "**/*secret*",
      "**/*token*",
      "**/*credential*",
      "**/middleware/**",
      "**/session/**"
    ],
    "moments": [
      {
        "at": "pre-pr",
        "mode": "audit"
      }
    ]
  },
  {
    "id": "justice",
    "domain": "correctness",
    "reference": "arcana/cards/justice.md",
    "globs": [],
    "moments": [
      {
        "at": "pre-pr",
        "mode": "audit"
      }
    ]
  },
  {
    "id": "temperance",
    "domain": "proportion",
    "reference": "arcana/cards/temperance.md",
    "globs": [],
    "moments": [
      {
        "at": "pre-pr",
        "mode": "review"
      }
    ]
  },
  {
    "id": "strength",
    "domain": "resilience",
    "reference": "arcana/cards/strength.md",
    "globs": [
      "**/client/**",
      "**/clients/**",
      "**/integrations/**",
      "**/adapters/**",
      "**/*gateway*"
    ],
    "moments": [
      {
        "at": "pre-pr",
        "mode": "audit"
      }
    ]
  },
  {
    "id": "devil",
    "domain": "abuse resistance",
    "reference": "arcana/cards/devil.md",
    "globs": [
      "**/*parser*",
      "**/*upload*",
      "**/handlers/**",
      "**/routes/**",
      "**/*quota*"
    ],
    "moments": [
      {
        "at": "pre-pr",
        "mode": "audit"
      }
    ]
  }
];
// arcana:hash:sha256 3b4250c7d6f40874e4c0f3a93ae1712e83ee3cbf9b6a392883d8f834be86c2ee
