// generated by arcana v0.1.0 from deck.yaml — edit deck.yaml, not this file
import { execFileSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

export function git(args) {
  try {
    return execFileSync('git', args, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe'] });
  } catch {
    return null;
  }
}

export function sha256(text) {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

export function repoRoot() {
  const out = git(['rev-parse', '--show-toplevel']);
  return out ? out.trim() : null;
}

export function pathspecs(globs) {
  return globs.map((g) => ':(glob)' + g);
}

/** Hash of the staged diff, restricted to globs when provided. */
export function stagedHash(globs) {
  const args = ['diff', '--cached'];
  if (globs.length > 0) args.push('--', ...pathspecs(globs));
  const diff = git(args);
  return diff === null ? null : sha256(diff);
}

/** Merge base with the upstream default branch, or null when indeterminable. */
export function branchBase() {
  for (const ref of ['origin/HEAD', 'origin/main', 'origin/master', 'main', 'master']) {
    const base = git(['merge-base', 'HEAD', ref]);
    if (base) return base.trim();
  }
  return null;
}

/** Hash of the branch diff against the merge base; null when no base exists. */
export function branchHash(globs) {
  const base = branchBase();
  if (!base) return null;
  const args = ['diff', base, 'HEAD'];
  if (globs.length > 0) args.push('--', ...pathspecs(globs));
  const diff = git(args);
  return diff === null ? null : sha256(diff);
}

export function markerDir() {
  const root = repoRoot();
  return root ? join(root, '.arcana', 'reviews') : null;
}

export function readMarker(id) {
  const dir = markerDir();
  if (!dir) return null;
  const file = join(dir, id + '.json');
  if (!existsSync(file)) return null;
  try {
    return JSON.parse(readFileSync(file, 'utf8'));
  } catch {
    return null;
  }
}

export function writeMarker(id, marker) {
  const dir = markerDir();
  if (!dir) return false;
  mkdirSync(dir, { recursive: true });
  const root = repoRoot();
  const ignoreFile = join(root, '.arcana', '.gitignore');
  if (!existsSync(ignoreFile)) writeFileSync(ignoreFile, '*\n');
  writeFileSync(join(dir, id + '.json'), JSON.stringify(marker, null, 2) + '\n');
  return true;
}
// arcana:hash:sha256 3976f14cba588db0e67bce1116cc3c2393b736f3e645b0d567d5bbe211b4f45b
