import { createHash } from 'node:crypto';

/** Markdown files use HTML comments; emitted scripts/config modules use JS comments. */
export type StampStyle = 'html' | 'js';

const HASH_LINES: Record<StampStyle, RegExp> = {
  html: /^<!-- arcana:hash:sha256 ([0-9a-f]{64}) -->$/,
  js: /^\/\/ arcana:hash:sha256 ([0-9a-f]{64})$/,
};

export function sha256(text: string): string {
  return createHash('sha256').update(text, 'utf8').digest('hex');
}

export function generatorNotice(version: string, style: StampStyle = 'html'): string {
  const text = `generated by arcana v${version} from deck.yaml — edit deck.yaml, not this file`;
  return style === 'html' ? `<!-- ${text} -->` : `// ${text}`;
}

function hashLine(hash: string, style: StampStyle): string {
  return style === 'html' ? `<!-- arcana:hash:sha256 ${hash} -->` : `// arcana:hash:sha256 ${hash}`;
}

/** Append the tamper-evident hash line. Content must end with a newline. */
export function stamp(content: string, style: StampStyle = 'html'): string {
  const body = content.endsWith('\n') ? content : `${content}\n`;
  return `${body}${hashLine(sha256(body), style)}\n`;
}

export type StampStatus = 'ok' | 'missing' | 'mismatch';

/** Split a stamped file into its body and hash line; undefined if unstamped. */
function splitStamp(fileText: string): { body: string; hash: string } | undefined {
  const withoutTrailing = fileText.endsWith('\n') ? fileText.slice(0, -1) : fileText;
  const lastBreak = withoutTrailing.lastIndexOf('\n');
  const lastLine = withoutTrailing.slice(lastBreak + 1);
  for (const pattern of Object.values(HASH_LINES)) {
    const match = pattern.exec(lastLine);
    if (match) return { body: withoutTrailing.slice(0, lastBreak + 1), hash: match[1]! };
  }
  return undefined;
}

export function isStamped(fileText: string): boolean {
  return splitStamp(fileText) !== undefined;
}

export function verifyStamp(fileText: string): StampStatus {
  const parts = splitStamp(fileText);
  if (!parts) return 'missing';
  return sha256(parts.body) === parts.hash ? 'ok' : 'mismatch';
}

/** Remove the hash line and any arcana generator notices (used by eject). */
export function stripStamp(fileText: string): string {
  const parts = splitStamp(fileText);
  const body = parts ? parts.body : fileText;
  return body
    .split('\n')
    .filter(
      (line) =>
        !/^<!-- generated by arcana v.* -->$/.test(line) &&
        !/^\/\/ generated by arcana v.*$/.test(line),
    )
    .join('\n')
    .replace(/^\n+/, '');
}
