import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { ownedFiles, runBuild } from '../../src/commands/build.js';
import { verifyStamp } from '../../src/compiler/hash.js';
import { makeTree, removeTree, VALID_CARD, VALID_PRECEPTS, VALID_RITE } from '../helpers.js';

const cleanups: string[] = [];
afterEach(() => {
  while (cleanups.length > 0) removeTree(cleanups.pop()!);
});

function registry(): string {
  const dir = makeTree({
    'cards/09-hermit.md': VALID_CARD,
    'rites/pentacles/migration.md': VALID_RITE,
    'precepts.md': VALID_PRECEPTS,
  });
  cleanups.push(dir);
  return dir;
}

function projectRoot(deck = 'version: 1\ncards:\n  - id: hermit\nrites:\n  - id: migration\n') {
  const root = makeTree({ 'deck.yaml': deck });
  cleanups.push(root);
  return root;
}

const OPTS = (reg: string) => ({ version: '0.0.0-test', registryDir: reg });

const FULL_EMISSION = [
  '.claude/agents/hermit.md',
  '.claude/arcana/bin/gate.mjs',
  '.claude/arcana/bin/mark-review.mjs',
  '.claude/arcana/guard-config.mjs',
  '.claude/arcana/lib.mjs',
  '.claude/rules/hermit.md',
  '.claude/skills/migration/SKILL.md',
  'CLAUDE.md',
  'arcana/cards/hermit.md',
  'arcana/precepts.md',
  'arcana/rites/migration.md',
];

describe('runBuild', () => {
  it('writes the full emission plus settings on first build', () => {
    const root = projectRoot();
    const summary = runBuild(root, OPTS(registry()));
    expect(summary.written).toEqual([...FULL_EMISSION, '.claude/settings.json']);
    expect(summary.deleted).toEqual([]);
    for (const path of FULL_EMISSION) {
      expect(verifyStamp(readFileSync(join(root, path), 'utf8')), path).toBe('ok');
    }
  });

  it('is idempotent: a second build writes nothing', () => {
    const root = projectRoot();
    const reg = registry();
    runBuild(root, OPTS(reg));
    const second = runBuild(root, OPTS(reg));
    expect(second.written).toEqual([]);
    expect(second.unchanged).toEqual(FULL_EMISSION);
  });

  it('restores tampered files (stamp still present) to byte-identical output', () => {
    const root = projectRoot();
    const reg = registry();
    runBuild(root, OPTS(reg));
    const first = readFileSync(join(root, 'CLAUDE.md'), 'utf8');
    writeFileSync(join(root, 'CLAUDE.md'), first.replace('Working agreement', 'My own rules'));
    runBuild(root, OPTS(reg));
    expect(readFileSync(join(root, 'CLAUDE.md'), 'utf8')).toBe(first);
  });

  it('refuses to clobber files arcana did not generate', () => {
    const root = projectRoot();
    const reg = registry();
    writeFileSync(join(root, 'CLAUDE.md'), '# My hand-written instructions\n');
    expect(() => runBuild(root, OPTS(reg))).toThrow(/not generated by arcana/);
    expect(readFileSync(join(root, 'CLAUDE.md'), 'utf8')).toBe('# My hand-written instructions\n');
  });

  it('prunes stamped files whose card left the deck', () => {
    const root = projectRoot();
    const reg = registry();
    runBuild(root, OPTS(reg));
    writeFileSync(join(root, 'deck.yaml'), 'version: 1\nrites:\n  - id: migration\n');
    const summary = runBuild(root, OPTS(reg));
    expect(summary.deleted).toEqual([
      '.claude/agents/hermit.md',
      '.claude/arcana/bin/gate.mjs',
      '.claude/arcana/bin/mark-review.mjs',
      '.claude/arcana/guard-config.mjs',
      '.claude/arcana/lib.mjs',
      '.claude/rules/hermit.md',
      'arcana/cards/hermit.md',
    ]);
    expect(existsSync(join(root, 'arcana/cards/hermit.md'))).toBe(false);
    expect(existsSync(join(root, '.claude/agents/hermit.md'))).toBe(false);
  });

  it('never deletes unstamped files in owned directories', () => {
    const root = projectRoot();
    const reg = registry();
    runBuild(root, OPTS(reg));
    const handWritten = join(root, 'arcana/cards/notes.md');
    writeFileSync(handWritten, 'my own notes\n');
    const summary = runBuild(root, OPTS(reg));
    expect(summary.deleted).toEqual([]);
    expect(existsSync(handWritten)).toBe(true);
  });
});

describe('ownedFiles', () => {
  it('lists only stamped files under owned roots', () => {
    const root = projectRoot();
    runBuild(root, OPTS(registry()));
    writeFileSync(join(root, 'arcana/cards/notes.md'), 'not stamped\n');
    expect(ownedFiles(root)).toEqual(FULL_EMISSION);
  });

  it('returns nothing before the first build', () => {
    expect(ownedFiles(projectRoot())).toEqual([]);
  });
});
