import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { afterEach, describe, expect, it } from 'vitest';
import { ownedFiles, runBuild } from '../../src/commands/build.js';
import { runEject } from '../../src/commands/eject.js';
import { isStamped } from '../../src/compiler/hash.js';
import { makeTree, removeTree, VALID_CARD, VALID_PRECEPTS, VALID_RITE } from '../helpers.js';

const cleanups: string[] = [];
afterEach(() => {
  while (cleanups.length > 0) removeTree(cleanups.pop()!);
});

function builtProject() {
  const reg = makeTree({
    'cards/09-hermit.md': VALID_CARD,
    'rites/pentacles/migration.md': VALID_RITE,
    'precepts.md': VALID_PRECEPTS,
  });
  const root = makeTree({
    'deck.yaml':
      'version: 1\ncards:\n  - id: hermit\nrites:\n  - id: migration\nbindings:\n  conduct:\n    - text: "Never commit secrets."\n      critical: true\n',
  });
  cleanups.push(reg, root);
  runBuild(root, { version: '0.0.0-test', registryDir: reg });
  return root;
}

describe('runEject', () => {
  it('strips stamps and notices from every generated file, which all remain', () => {
    const root = builtProject();
    const before = ownedFiles(root);
    expect(before.length).toBeGreaterThan(0);

    const summary = runEject(root);
    expect(summary.ejected).toEqual(before);

    for (const rel of before) {
      const content = readFileSync(join(root, rel), 'utf8');
      expect(existsSync(join(root, rel)), rel).toBe(true);
      expect(isStamped(content), rel).toBe(false);
      expect(content, rel).not.toContain('generated by arcana');
    }
  });

  it('leaves the working content intact', () => {
    const root = builtProject();
    runEject(root);
    const core = readFileSync(join(root, 'CLAUDE.md'), 'utf8');
    expect(core).toContain('# Working agreement');
    expect(core).toContain('Never commit secrets.');
    const gate = readFileSync(join(root, '.claude/arcana/bin/gate.mjs'), 'utf8');
    expect(gate).toContain('process.exit(2)');
  });

  it('leaves settings.json hook registrations in place so gates keep working', () => {
    const root = builtProject();
    runEject(root);
    const settings = JSON.parse(readFileSync(join(root, '.claude/settings.json'), 'utf8'));
    expect(JSON.stringify(settings.hooks.PreToolUse)).toContain('.claude/arcana/bin/gate.mjs');
  });

  it('is terminal: arcana no longer owns anything afterwards', () => {
    const root = builtProject();
    runEject(root);
    expect(ownedFiles(root)).toEqual([]);
    expect(runEject(root).ejected).toEqual([]);
  });
});
